sudo: required
services:
  - docker

before_install:
  - docker build -t captainxkid/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true captainxkid/react-test npm test

after_success:
  - docker build -t captainxkid/multi-client ./client
  - docker build -t captainxkid/multi-nginx ./nginx
  - docker build -t captainxkid/multi-server ./server
  - docker build -t captainxkid/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin #login to docker CLI
  # push images in docker hub
  - docker push captainxkid/multi-client
  - docker push captainxkid/multi-nginx
  - docker push captainxkid/multi-server
  - docker push captainxkid/multi-worker

